### ISSUE TITLE
Fix oplog index parsing error when reading from S3

### ISSUE THREAD

**Issue by afsalthaj** [golemcloud/golem#580]
Please see the below error :

https://github.com/golemcloud/golem-cloud/actions/runs/9463481259/job/26069194051?pr=1398

```
e matching version with:
cargo install golem-cli@0.1.0

Updated component with ID cc946cb1-983c-4728-a2ec-2df8778dfa4a. New version: 3. Component size is 430072 bytes.
Component name: shopping-cart-ci-rust-1-ubuntu-latest-large.
Exports:
	golem:it/api/initialize-cart(user-id: string)
	golem:it/api/add-item(item: record { product-id: string, name: string, price: float32, quantity: u32 })
	golem:it/api/remove-item(product-id: string)
	golem:it/api/update-item-quantity(product-id: string, quantity: u32)
	golem:it/api/checkout() -> variant { error(string), success(record { order-id: string }) }
	golem:it/api/get-cart-contents() -> list<record { product-id: string, name: string, price: float32, quantity: u32 }>
# Invoke worker shopping-cart-1-ci-rust-1-ubuntu-latest-large
Warning: golem-cli 0.0.102 is older than the targeted Golem servers (0.1.0)
Install the matching version with:
cargo install golem-cli@0.1.0

Error: InternalError: GolemErrorBody { golem_error: RuntimeError(GolemErrorRuntimeError { details: "status: Cancelled, message: \"h2 protocol error: http2 error: stream error received: stream no longer needed\", details: [], metadata: MetadataMap { headers: {} }" }) }
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
Error: Process completed with ex

```

and the cause is

```

{"timestamp":"2024-06-11T10:06:08.330721Z","level":"INFO","message":"Recovering workers","target":"golem_worker_executor_base::durable_host","span":{"api":"assign_shards","name":"grpc_request"},"spans":[{"api":"assign_shards","name":"grpc_request"}]}
{"timestamp":"2024-06-11T10:06:08.970916Z","level":"INFO","message":"Finished recovering workers","target":"golem_worker_executor_base::durable_host","span":{"api":"assign_shards","name":"grpc_request"},"spans":[{"api":"assign_shards","name":"grpc_request"}]}
{"timestamp":"2024-06-11T10:06:08.970958Z","level":"INFO","message":"gRPC request succeeded in 640ms","target":"golem_worker_executor_base::metrics::grpc","span":{"api":"assign_shards","name":"grpc_request"},"spans":[{"api":"assign_shards","name":"grpc_request"}]}
{"timestamp":"2024-06-11T10:18:12.424849Z","level":"INFO","message":"Get workers for component: cc946cb1-983c-4728-a2ec-2df8778dfa4a, filter: name == shopping-cart-1-ci-rust-1-ubuntu-latest-large, cursor: 0/0, count: 2, precise: true","target":"golem_worker_executor_base::services::worker_enumeration","span":{"api":"get_workers_metadata","component_id":"cc946cb1-983c-4728-a2ec-2df8778dfa4a","name":"grpc_request"},"spans":[{"api":"get_workers_metadata","component_id":"cc946cb1-983c-4728-a2ec-2df8778dfa4a","name":"grpc_request"}]}
{"timestamp":"2024-06-11T10:18:12.427658Z","level":"INFO","message":"identity cache miss occurred; added new identity (took Ok(3.71819ms))","target":"aws_smithy_runtime::client::identity::cache::lazy","span":{"name":"lazy_load_identity"},"spans":[{"api":"get_worker_metadata","worker_id":"cc946cb1-983c-4728-a2ec-2df8778dfa4a/shopping-cart-1-ci-rust-1-ubuntu-latest-large","name":"grpc_request"},{"name":"lazy_load_identity"}]}
{"timestamp":"2024-06-11T10:18:12.446553Z","level":"INFO","message":"gRPC request succeeded in 21ms","target":"golem_worker_executor_base::metrics::grpc","span":{"api":"get_workers_metadata","component_id":"cc946cb1-983c-4728-a2ec-2df8778dfa4a","name":"grpc_request"},"spans":[{"api":"get_workers_metadata","component_id":"cc946cb1-983c-4728-a2ec-2df8778dfa4a","name":"grpc_request"}]}
{"timestamp":"2024-06-11T10:18:12.461603Z","level":"ERROR","message":"Checking existence of blob at 242553885714-component-store-dev::\"root/cc946cb1-983c-4728-a2ec-2df8778dfa4a/shopping-cart-1-ci-rust-1-ubuntu-latest-large\" failed with non-retriable error after 1 attempts with service error","target":"golem_common::retries","span":{"api":"get_worker_metadata","worker_id":"cc946cb1-983c-4728-a2ec-2df8778dfa4a/shopping-cart-1-ci-rust-1-ubuntu-latest-large","name":"grpc_request"},"spans":[{"api":"get_worker_metadata","worker_id":"cc946cb1-983c-4728-a2ec-2df8778dfa4a/shopping-cart-1-ci-rust-1-ubuntu-latest-large","name":"grpc_request"}]}
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/git/checkouts/golem-d4897a888ca93a37/e1d0750/golem-worker-executor-base/src/services/oplog/blob.rs:268:32:
failed to parse oplog index from path: "root/cc946cb1-983c-4728-a2ec-2df8778dfa4a/shopping-cart-1-ci-rust-1-ubuntu-latest-large/__dir_marker"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: golem_worker_executor_base::services::oplog::blob::BlobOplogArchive::path_to_oplog_index
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   4: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   5: <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter
   6: <golem_worker_executor_base::services::oplog::blob::BlobOplogArchiveService as golem_worker_executor_base::services::oplog::multilayer::OplogArchiveService>::open::{{closure}}
   7: <golem_worker_executor_base::services::oplog::blob::BlobOplogArchiveService as golem_worker_executor_base::services::oplog::multilayer::OplogArchiveService>::read::{{closure}}
   8: <golem_worker_executor_base::services::oplog::multilayer::MultiLayerOplogService as golem_worker_executor_base::services::oplog::OplogService>::read::{{closure}}
   9: <golem_worker_executor_base::services::worker::DefaultWorkerService as golem_worker_executor_base::services::worker::WorkerService>::get::{{closure}}
  10: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  11: <golem_worker_executor_base::grpc::WorkerExecutorImpl<Ctx,Svcs> as golem_api_grpc::proto::golem::workerexecutor::worker_executor_server::WorkerExecutor>::get_worker_metadata::{{closure}}
  12: <<golem_api_grpc::proto::golem::workerexecutor::worker_executor_server::WorkerExecutorServer<T> as tower_service::Service<http::request::Request<B>>>::call::GetWorkerMetadataSvc<T> as tonic::server::service::UnaryService<golem_api_grpc::proto::golem::workerexecutor::GetWorkerMetadataRequest>>::call::{{closure}}
  13: <golem_api_grpc::proto::golem::workerexecutor::worker_executor_server::WorkerExecutorServer<T> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
  14: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  16: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
  17: <tonic::transport::service::router::RoutesFuture as core::future::future::Future>::poll
  18: <tower::util::either::Either<A,B> as core::future::future::Future>::poll
  19: <tonic::transport::server::SvcFuture<F> as core::future::future::Future>::poll
  20: <hyper::proto::h2::server::H2Stream<F,B> as core::future::future::Future>::poll
  21: tokio::runtime::task::harness::Harness<T,S>::poll
  22: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  23: tokio::runtime::scheduler::multi_thread::worker::Context::run
  24: tokio::runtime::context::set_scheduler
  25: tokio::runtime::context::runtime::enter_runtime
  26: tokio::runtime::scheduler::multi_thread::worker::run
  27: tokio::runtime::task::core::Core<T,S>::poll
  28: tokio::runtime::task::harness::Harness<T,S>::poll
  29: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
^C
```

**Comment by afsalthaj** [comment]
As of now we have a single bucket, and assuming prefixes will save us from using it for different buckets.
The first thing is to isolate various use cases with different buckets, and take it for a team discussion
